# Generated by Django 4.1.2 on 2022-10-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoAuthor',
            new_name='Advisor',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='CoAdvisor',
        ),
        migrations.AlterField(
            model_name='monography',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monografias.author'),
        ),
        migrations.AlterField(
            model_name='monography',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
